stages:
  extract-alexa:
    cmd: unzip data/raw/alexa_1M.zip -d data/extract-alexa/
    deps:
    - data/raw/alexa_1M.zip
    outs:
    - data/extract-alexa/
  prepare-alexa:
    cmd: python src/preparation/alexa_prepare.py data/extract-alexa/alexa_1M.csv data/prepare-alexa/
    deps:
    - data/extract-alexa/alexa_1M.csv
    - src/preparation/alexa_prepare.py
    params:
    - preparation.seed
    outs:
    - data/prepare-alexa/
  prepare-dga:
    cmd: python src/preparation/dga_prepare.py data/raw/dga_domains.txt data/prepare-dga/
    deps:
    - data/raw/dga_domains.txt
    - src/preparation/dga_prepare.py
    outs:
    - data/prepare-dga/
  prepare-words:
    cmd: python src/preparation/words_prepare.py data/raw/words.txt data/prepare-words/
    deps:
    - data/raw/words.txt
    - src/preparation/words_prepare.py
    outs:
    - data/prepare-words/
